use spirv_builder::SpirvBuilder;
use std::error::Error;
use std::fs;

fn main() -> Result<(), Box<dyn Error>> {
    // Prevent recursion when building the shader itself
    if std::env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default() == "spirv" {
        return Ok(());
    }

    let result = SpirvBuilder::new("planet-shader", "spirv-unknown-spv1.5")
        .build()?;

    let spv_path = result.module.unwrap_single();
    let spv_bytes = fs::read(spv_path)?;

    // Parse SPIR-V to naga module
    let module = naga::front::spv::parse_u8_slice(&spv_bytes, &naga::front::spv::Options::default())?;

    // Validate the module
    let info = naga::valid::Validator::new(
        naga::valid::ValidationFlags::all(),
        naga::valid::Capabilities::all(),
    ).validate(&module)?;

    // Transpile SPIR-V module to WGSL
    let wgsl_code = naga::back::wgsl::write_string(&module, &info, naga::back::wgsl::WriterFlags::empty())?;

    // Extract the Vec3Shared struct
    let struct_start = wgsl_code.find("struct type_1 {").ok_or("Could not find type_1 struct")?;
    let struct_end = wgsl_code[struct_start..].find("}").ok_or("Could not find end of type_1 struct")? + struct_start + 1;
    let struct_def = wgsl_code[struct_start..struct_end].replace("struct type_1", "struct Vec3Shared");

    // Extract the snoise3_shared function
    let func_start = wgsl_code.find("fn function_(").ok_or("Could not find function_ definition")?;
    let func_end = wgsl_code.find("fn function_1(").ok_or("Could not find function_1 definition")?;
    let func_def = wgsl_code[func_start..func_end].trim()
        .replace("fn function_(", "fn snoise3_shared(")
        .replace("param: type_1", "param: Vec3Shared");

    // Combine into a clean output file
    let final_wgsl = format!(
        "// Generated by rust-gpu and naga. Do not edit.\n\n{}\n\n{}",
        struct_def, func_def
    );

    // Write generated WGSL to assets folder
    fs::create_dir_all("assets/shaders")?;
    fs::write("assets/shaders/simplex.wgsl", &final_wgsl)?;

    // Integrate with the terrain shader template
    let template = fs::read_to_string("assets/shaders/terrain.template.wgsl")?;
    let final_shader = template.replace("// {{SIMPLEX_NOISE}}", &final_wgsl);
    fs::write("assets/shaders/terrain.wgsl", final_shader)?;

    println!("cargo:rerun-if-changed=planet-shader/src/lib.rs");
    println!("cargo:rerun-if-changed=assets/shaders/terrain.template.wgsl");

    Ok(())
}

