struct ViewUniforms {
    view_proj: mat4x4<f32>,
    light_dir: vec3<f32>,
    ambient: f32,
    camera_pos: vec3<f32>,
    show_wireframe: f32,
}

struct Globals {
    camera_pos: vec3<f32>,
    planet_radius: f32,
    planet_center: vec3<f32>,
    noise_frequency: f32,
    noise_amplitude: f32,
    lod_split_factor: f32,
    frustum_planes: array<vec4<f32>, 6>,
}

struct VertexInput {
    position: vec4<f32>,
    normal: vec4<f32>,
}

@group(0) @binding(0) var<uniform> view_uniforms: ViewUniforms;
@group(0) @binding(1) var<storage, read> vertices: array<VertexInput>;
@group(0) @binding(2) var<uniform> globals: Globals;

struct VertexOutput {
    @builtin(position) clip_position: vec4<f32>,
    @location(0) world_position: vec3<f32>,
    @location(1) normal: vec3<f32>,
    @location(2) barycentric: vec3<f32>,
}

// Generated by rust-gpu and naga. Do not edit.

struct Vec3Shared {
    member: f32,
    member_1: f32,
    member_2: f32,
}

fn snoise3_shared(param: Vec3Shared) -> f32 {
    var phi_757_: bool;
    var phi_772_: bool;
    var phi_787_: bool;
    var phi_830_: f32;
    var phi_842_: f32;
    var phi_854_: f32;
    var phi_866_: bool;
    var phi_881_: bool;
    var phi_896_: bool;
    var phi_938_: f32;
    var phi_950_: f32;
    var phi_962_: f32;
    var phi_1330_: bool;
    var phi_1345_: bool;
    var phi_1360_: bool;
    var phi_1375_: bool;
    var phi_1427_: Vec3Shared;
    var phi_1429_: Vec3Shared;
    var phi_1532_: Vec3Shared;
    var phi_1534_: Vec3Shared;
    var phi_1637_: Vec3Shared;
    var phi_1639_: Vec3Shared;
    var phi_1742_: Vec3Shared;
    var phi_1744_: Vec3Shared;

    let _e35 = (0.6666667f * ((param.member + param.member_1) + param.member_2));
    let _e36 = (_e35 - param.member);
    let _e37 = (_e35 - param.member_1);
    let _e38 = (_e35 - param.member_2);
    let _e39 = round(_e36);
    let _e40 = round(_e37);
    let _e41 = round(_e38);
    let _e42 = (_e36 - _e39);
    let _e43 = (_e37 - _e40);
    let _e44 = (_e38 - _e41);
    let _e45 = abs(_e42);
    let _e46 = abs(_e43);
    let _e47 = abs(_e44);
    if (_e46 != _e46) {
        phi_757_ = true;
    } else {
        phi_757_ = (_e47 >= _e46);
    }
    let _e51 = phi_757_;
    if (_e47 != _e47) {
        phi_772_ = true;
    } else {
        phi_772_ = (_e45 >= _e47);
    }
    let _e56 = phi_772_;
    if (_e45 != _e45) {
        phi_787_ = true;
    } else {
        phi_787_ = (_e46 >= _e45);
    }
    let _e61 = phi_787_;
    if (_e42 < 0f) {
        phi_830_ = -1f;
    } else {
        phi_830_ = select(0f, 1f, (_e42 > 0f));
    }
    let _e73 = phi_830_;
    if (_e43 < 0f) {
        phi_842_ = -1f;
    } else {
        phi_842_ = select(0f, 1f, (_e43 > 0f));
    }
    let _e78 = phi_842_;
    if (_e44 < 0f) {
        phi_854_ = -1f;
    } else {
        phi_854_ = select(0f, 1f, (_e44 > 0f));
    }
    let _e83 = phi_854_;
    let _e87 = (_e39 + (select(1f, 0f, (_e45 < select(_e46, _e47, _e51))) * _e73));
    let _e88 = (_e40 + (select(1f, 0f, (_e46 < select(_e47, _e45, _e56))) * _e78));
    let _e89 = (_e41 + (select(1f, 0f, (_e47 < select(_e45, _e46, _e61))) * _e83));
    let _e90 = (_e36 - _e87);
    let _e91 = (_e37 - _e88);
    let _e92 = (_e38 - _e89);
    let _e93 = (_e36 + 144.5f);
    let _e94 = (_e37 + 144.5f);
    let _e95 = (_e38 + 144.5f);
    let _e96 = round(_e93);
    let _e97 = round(_e94);
    let _e98 = round(_e95);
    let _e99 = (_e93 - _e96);
    let _e100 = (_e94 - _e97);
    let _e101 = (_e95 - _e98);
    let _e102 = abs(_e99);
    let _e103 = abs(_e100);
    let _e104 = abs(_e101);
    if (_e103 != _e103) {
        phi_866_ = true;
    } else {
        phi_866_ = (_e104 >= _e103);
    }
    let _e108 = phi_866_;
    if (_e104 != _e104) {
        phi_881_ = true;
    } else {
        phi_881_ = (_e102 >= _e104);
    }
    let _e113 = phi_881_;
    if (_e102 != _e102) {
        phi_896_ = true;
    } else {
        phi_896_ = (_e103 >= _e102);
    }
    let _e118 = phi_896_;
    if (_e99 < 0f) {
        phi_938_ = -1f;
    } else {
        phi_938_ = select(0f, 1f, (_e99 > 0f));
    }
    let _e130 = phi_938_;
    if (_e100 < 0f) {
        phi_950_ = -1f;
    } else {
        phi_950_ = select(0f, 1f, (_e100 > 0f));
    }
    let _e135 = phi_950_;
    if (_e101 < 0f) {
        phi_962_ = -1f;
    } else {
        phi_962_ = select(0f, 1f, (_e101 > 0f));
    }
    let _e140 = phi_962_;
    let _e144 = (_e96 + (select(1f, 0f, (_e102 < select(_e103, _e104, _e108))) * _e130));
    let _e145 = (_e97 + (select(1f, 0f, (_e103 < select(_e104, _e102, _e113))) * _e135));
    let _e146 = (_e98 + (select(1f, 0f, (_e104 < select(_e102, _e103, _e118))) * _e140));
    let _e147 = (_e93 - _e144);
    let _e148 = (_e94 - _e145);
    let _e149 = (_e95 - _e146);
    let _e162 = (_e39 - (floor((_e39 * 0.0034602077f)) * 289f));
    let _e163 = (_e87 - (floor((_e87 * 0.0034602077f)) * 289f));
    let _e164 = (_e96 - (floor((_e96 * 0.0034602077f)) * 289f));
    let _e165 = (_e144 - (floor((_e144 * 0.0034602077f)) * 289f));
    let _e178 = (_e162 - (floor((_e162 * 0.0034602077f)) * 289f));
    let _e179 = (_e163 - (floor((_e163 * 0.0034602077f)) * 289f));
    let _e180 = (_e164 - (floor((_e164 * 0.0034602077f)) * 289f));
    let _e181 = (_e165 - (floor((_e165 * 0.0034602077f)) * 289f));
    let _e190 = (_e178 * ((_e178 * 34f) + 133f));
    let _e191 = (_e179 * ((_e179 * 34f) + 133f));
    let _e192 = (_e180 * ((_e180 * 34f) + 133f));
    let _e193 = (_e181 * ((_e181 * 34f) + 133f));
    let _e210 = ((_e190 - (floor((_e190 * 0.0034602077f)) * 289f)) + _e40);
    let _e211 = ((_e191 - (floor((_e191 * 0.0034602077f)) * 289f)) + _e88);
    let _e212 = ((_e192 - (floor((_e192 * 0.0034602077f)) * 289f)) + _e97);
    let _e213 = ((_e193 - (floor((_e193 * 0.0034602077f)) * 289f)) + _e145);
    let _e226 = (_e210 - (floor((_e210 * 0.0034602077f)) * 289f));
    let _e227 = (_e211 - (floor((_e211 * 0.0034602077f)) * 289f));
    let _e228 = (_e212 - (floor((_e212 * 0.0034602077f)) * 289f));
    let _e229 = (_e213 - (floor((_e213 * 0.0034602077f)) * 289f));
    let _e242 = (_e226 - (floor((_e226 * 0.0034602077f)) * 289f));
    let _e243 = (_e227 - (floor((_e227 * 0.0034602077f)) * 289f));
    let _e244 = (_e228 - (floor((_e228 * 0.0034602077f)) * 289f));
    let _e245 = (_e229 - (floor((_e229 * 0.0034602077f)) * 289f));
    let _e254 = (_e242 * ((_e242 * 34f) + 133f));
    let _e255 = (_e243 * ((_e243 * 34f) + 133f));
    let _e256 = (_e244 * ((_e244 * 34f) + 133f));
    let _e257 = (_e245 * ((_e245 * 34f) + 133f));
    let _e274 = ((_e254 - (floor((_e254 * 0.0034602077f)) * 289f)) + _e41);
    let _e275 = ((_e255 - (floor((_e255 * 0.0034602077f)) * 289f)) + _e89);
    let _e276 = ((_e256 - (floor((_e256 * 0.0034602077f)) * 289f)) + _e98);
    let _e277 = ((_e257 - (floor((_e257 * 0.0034602077f)) * 289f)) + _e146);
    let _e290 = (_e274 - (floor((_e274 * 0.0034602077f)) * 289f));
    let _e291 = (_e275 - (floor((_e275 * 0.0034602077f)) * 289f));
    let _e292 = (_e276 - (floor((_e276 * 0.0034602077f)) * 289f));
    let _e293 = (_e277 - (floor((_e277 * 0.0034602077f)) * 289f));
    let _e306 = (_e290 - (floor((_e290 * 0.0034602077f)) * 289f));
    let _e307 = (_e291 - (floor((_e291 * 0.0034602077f)) * 289f));
    let _e308 = (_e292 - (floor((_e292 * 0.0034602077f)) * 289f));
    let _e309 = (_e293 - (floor((_e293 * 0.0034602077f)) * 289f));
    let _e318 = (_e306 * ((_e306 * 34f) + 133f));
    let _e319 = (_e307 * ((_e307 * 34f) + 133f));
    let _e320 = (_e308 * ((_e308 * 34f) + 133f));
    let _e321 = (_e309 * ((_e309 * 34f) + 133f));
    let _e334 = (_e318 - (floor((_e318 * 0.0034602077f)) * 289f));
    let _e335 = (_e319 - (floor((_e319 * 0.0034602077f)) * 289f));
    let _e336 = (_e320 - (floor((_e320 * 0.0034602077f)) * 289f));
    let _e337 = (_e321 - (floor((_e321 * 0.0034602077f)) * 289f));
    let _e350 = (_e334 - (floor((_e334 * 0.020833334f)) * 48f));
    let _e351 = (_e335 - (floor((_e335 * 0.020833334f)) * 48f));
    let _e352 = (_e336 - (floor((_e336 * 0.020833334f)) * 48f));
    let _e353 = (_e337 - (floor((_e337 * 0.020833334f)) * 48f));
    let _e374 = (0.5f - (((_e42 * _e42) + (_e43 * _e43)) + (_e44 * _e44)));
    let _e375 = (0.5f - (((_e90 * _e90) + (_e91 * _e91)) + (_e92 * _e92)));
    let _e376 = (0.5f - (((_e99 * _e99) + (_e100 * _e100)) + (_e101 * _e101)));
    let _e377 = (0.5f - (((_e147 * _e147) + (_e148 * _e148)) + (_e149 * _e149)));
    if (_e374 != _e374) {
        phi_1330_ = true;
    } else {
        phi_1330_ = (0f >= _e374);
    }
    let _e381 = phi_1330_;
    let _e382 = select(_e374, 0f, _e381);
    if (_e375 != _e375) {
        phi_1345_ = true;
    } else {
        phi_1345_ = (0f >= _e375);
    }
    let _e386 = phi_1345_;
    let _e387 = select(_e375, 0f, _e386);
    if (_e376 != _e376) {
        phi_1360_ = true;
    } else {
        phi_1360_ = (0f >= _e376);
    }
    let _e391 = phi_1360_;
    let _e392 = select(_e376, 0f, _e391);
    if (_e377 != _e377) {
        phi_1375_ = true;
    } else {
        phi_1375_ = (0f >= _e377);
    }
    let _e396 = phi_1375_;
    let _e397 = select(_e377, 0f, _e396);
    let _e398 = (_e382 * _e382);
    let _e399 = (_e387 * _e387);
    let _e400 = (_e392 * _e392);
    let _e401 = (_e397 * _e397);
    let _e406 = floor(_e350);
    let _e408 = floor((_e350 * 0.5f));
    let _e410 = floor((_e350 * 0.25f));
    let _e416 = (((_e406 - (floor((_e406 * 0.5f)) * 2f)) * 2f) - 1f);
    let _e422 = (((_e408 - (floor((_e408 * 0.5f)) * 2f)) * 2f) - 1f);
    let _e428 = (((_e410 - (floor((_e410 * 0.5f)) * 2f)) * 2f) - 1f);
    let _e430 = floor((_e350 * 0.0625f));
    let _e437 = select(0i, select(select(i32(_e430), i32(-2147483648), (_e430 < -2147483600f)), 2147483647i, (_e430 > 2147483500f)), (_e430 == _e430));
    if (_e437 == 0i) {
        phi_1429_ = Vec3Shared(0f, _e422, _e428);
    } else {
        if (_e437 == 1i) {
            phi_1427_ = Vec3Shared(_e416, 0f, _e428);
        } else {
            phi_1427_ = Vec3Shared(_e416, _e422, 0f);
        }
        let _e444 = phi_1427_;
        phi_1429_ = _e444;
    }
    let _e446 = phi_1429_;
    let _e448 = floor((_e350 * 0.125f));
    let _e452 = (_e448 - (floor((_e448 * 0.5f)) * 2f));
    let _e453 = (1f - _e452);
    let _e486 = ((1f - (0.04294244f * _e452)) * 32.802013f);
    let _e490 = floor(_e351);
    let _e492 = floor((_e351 * 0.5f));
    let _e494 = floor((_e351 * 0.25f));
    let _e500 = (((_e490 - (floor((_e490 * 0.5f)) * 2f)) * 2f) - 1f);
    let _e506 = (((_e492 - (floor((_e492 * 0.5f)) * 2f)) * 2f) - 1f);
    let _e512 = (((_e494 - (floor((_e494 * 0.5f)) * 2f)) * 2f) - 1f);
    let _e514 = floor((_e351 * 0.0625f));
    let _e521 = select(0i, select(select(i32(_e514), i32(-2147483648), (_e514 < -2147483600f)), 2147483647i, (_e514 > 2147483500f)), (_e514 == _e514));
    if (_e521 == 0i) {
        phi_1534_ = Vec3Shared(0f, _e506, _e512);
    } else {
        if (_e521 == 1i) {
            phi_1532_ = Vec3Shared(_e500, 0f, _e512);
        } else {
            phi_1532_ = Vec3Shared(_e500, _e506, 0f);
        }
        let _e528 = phi_1532_;
        phi_1534_ = _e528;
    }
    let _e530 = phi_1534_;
    let _e532 = floor((_e351 * 0.125f));
    let _e536 = (_e532 - (floor((_e532 * 0.5f)) * 2f));
    let _e537 = (1f - _e536);
    let _e570 = ((1f - (0.04294244f * _e536)) * 32.802013f);
    let _e574 = floor(_e352);
    let _e576 = floor((_e352 * 0.5f));
    let _e578 = floor((_e352 * 0.25f));
    let _e584 = (((_e574 - (floor((_e574 * 0.5f)) * 2f)) * 2f) - 1f);
    let _e590 = (((_e576 - (floor((_e576 * 0.5f)) * 2f)) * 2f) - 1f);
    let _e596 = (((_e578 - (floor((_e578 * 0.5f)) * 2f)) * 2f) - 1f);
    let _e598 = floor((_e352 * 0.0625f));
    let _e605 = select(0i, select(select(i32(_e598), i32(-2147483648), (_e598 < -2147483600f)), 2147483647i, (_e598 > 2147483500f)), (_e598 == _e598));
    if (_e605 == 0i) {
        phi_1639_ = Vec3Shared(0f, _e590, _e596);
    } else {
        if (_e605 == 1i) {
            phi_1637_ = Vec3Shared(_e584, 0f, _e596);
        } else {
            phi_1637_ = Vec3Shared(_e584, _e590, 0f);
        }
        let _e612 = phi_1637_;
        phi_1639_ = _e612;
    }
    let _e614 = phi_1639_;
    let _e616 = floor((_e352 * 0.125f));
    let _e620 = (_e616 - (floor((_e616 * 0.5f)) * 2f));
    let _e621 = (1f - _e620);
    let _e654 = ((1f - (0.04294244f * _e620)) * 32.802013f);
    let _e658 = floor(_e353);
    let _e660 = floor((_e353 * 0.5f));
    let _e662 = floor((_e353 * 0.25f));
    let _e668 = (((_e658 - (floor((_e658 * 0.5f)) * 2f)) * 2f) - 1f);
    let _e674 = (((_e660 - (floor((_e660 * 0.5f)) * 2f)) * 2f) - 1f);
    let _e680 = (((_e662 - (floor((_e662 * 0.5f)) * 2f)) * 2f) - 1f);
    let _e682 = floor((_e353 * 0.0625f));
    let _e689 = select(0i, select(select(i32(_e682), i32(-2147483648), (_e682 < -2147483600f)), 2147483647i, (_e682 > 2147483500f)), (_e682 == _e682));
    if (_e689 == 0i) {
        phi_1744_ = Vec3Shared(0f, _e674, _e680);
    } else {
        if (_e689 == 1i) {
            phi_1742_ = Vec3Shared(_e668, 0f, _e680);
        } else {
            phi_1742_ = Vec3Shared(_e668, _e674, 0f);
        }
        let _e696 = phi_1742_;
        phi_1744_ = _e696;
    }
    let _e698 = phi_1744_;
    let _e700 = floor((_e353 * 0.125f));
    let _e704 = (_e700 - (floor((_e700 * 0.5f)) * 2f));
    let _e705 = (1f - _e704);
    let _e738 = ((1f - (0.04294244f * _e704)) * 32.802013f);
    return (((((_e398 * _e398) * (((_e42 * (((_e446.member * 1.2247449f) + ((_e453 * _e416) + (_e452 * (_e446.member + ((_e422 * _e446.member_2) - (_e446.member_1 * _e428)))))) * _e486)) + (_e43 * (((_e446.member_1 * 1.2247449f) + ((_e453 * _e422) + (_e452 * (_e446.member_1 + ((_e428 * _e446.member) - (_e446.member_2 * _e416)))))) * _e486))) + (_e44 * (((_e446.member_2 * 1.2247449f) + ((_e453 * _e428) + (_e452 * (_e446.member_2 + ((_e416 * _e446.member_1) - (_e446.member * _e422)))))) * _e486)))) + ((_e399 * _e399) * (((_e90 * (((_e530.member * 1.2247449f) + ((_e537 * _e500) + (_e536 * (_e530.member + ((_e506 * _e530.member_2) - (_e530.member_1 * _e512)))))) * _e570)) + (_e91 * (((_e530.member_1 * 1.2247449f) + ((_e537 * _e506) + (_e536 * (_e530.member_1 + ((_e512 * _e530.member) - (_e530.member_2 * _e500)))))) * _e570))) + (_e92 * (((_e530.member_2 * 1.2247449f) + ((_e537 * _e512) + (_e536 * (_e530.member_2 + ((_e500 * _e530.member_1) - (_e530.member * _e506)))))) * _e570))))) + ((_e400 * _e400) * (((_e99 * (((_e614.member * 1.2247449f) + ((_e621 * _e584) + (_e620 * (_e614.member + ((_e590 * _e614.member_2) - (_e614.member_1 * _e596)))))) * _e654)) + (_e100 * (((_e614.member_1 * 1.2247449f) + ((_e621 * _e590) + (_e620 * (_e614.member_1 + ((_e596 * _e614.member) - (_e614.member_2 * _e584)))))) * _e654))) + (_e101 * (((_e614.member_2 * 1.2247449f) + ((_e621 * _e596) + (_e620 * (_e614.member_2 + ((_e584 * _e614.member_1) - (_e614.member * _e590)))))) * _e654))))) + ((_e401 * _e401) * (((_e147 * (((_e698.member * 1.2247449f) + ((_e705 * _e668) + (_e704 * (_e698.member + ((_e674 * _e698.member_2) - (_e698.member_1 * _e680)))))) * _e738)) + (_e148 * (((_e698.member_1 * 1.2247449f) + ((_e705 * _e674) + (_e704 * (_e698.member_1 + ((_e680 * _e698.member) - (_e698.member_2 * _e668)))))) * _e738))) + (_e149 * (((_e698.member_2 * 1.2247449f) + ((_e705 * _e680) + (_e704 * (_e698.member_2 + ((_e668 * _e698.member_1) - (_e698.member * _e674)))))) * _e738)))));
}

fn sample_noise(p: vec3<f32>) -> f32 {
    return snoise3_shared(Vec3Shared(p.x, p.y, p.z));
}

struct DisplacementData {
    displacement: f32,
    mountain_factor: f32,
    land_mask: f32,
    temp_noise: f32,
    humid_noise: f32,
}

fn get_displacement(pos_unit: vec3<f32>) -> DisplacementData {
    let f0 = globals.noise_frequency;
    
    // Sample shared noise frequencies to stay within the 33-call budget (9 unique calls)
    let n_f0_3 = sample_noise(pos_unit * (f0 * 0.3));
    let n_f0_6 = sample_noise(pos_unit * (f0 * 0.6));
    let n_f0_12 = sample_noise(pos_unit * (f0 * 1.2));
    let n_f0 = sample_noise(pos_unit * f0);
    let n_f0_2 = sample_noise(pos_unit * (f0 * 2.0));
    let n_f0_4 = sample_noise(pos_unit * (f0 * 4.0));
    let n_f0_8 = sample_noise(pos_unit * (f0 * 8.0));
    let n_f0_16 = sample_noise(pos_unit * (f0 * 16.0));
    let n_f0_32 = sample_noise(pos_unit * (f0 * 32.0));

    // 1. Continent / Ocean mask (large scale) - 3 Octaves for organic coastlines
    let continent_noise = n_f0_3 + n_f0_6 * 0.4 + n_f0_12 * 0.15;
    let land_mask = clamp(continent_noise * 2.0 + 0.3, 0.0, 1.0);

    // 2. Mountain selector (where mountain ranges form) - 2 Octaves for winding chains
    let mountain_selector = n_f0_6 + n_f0_12 * 0.3;
    let mountain_factor = clamp(mountain_selector * 1.8 - 0.2, 0.0, 1.0) * land_mask;

    // 3. Plains elevation (bumpy hills / plains) - 6 Octaves (ultra-bumpiness)
    let plains = n_f0 * 0.25 + 0.25 + n_f0_2 * 0.12 + n_f0_4 * 0.06 + n_f0_8 * 0.03 + n_f0_16 * 0.015 + n_f0_32 * 0.008;

    // 4. Mountain elevation (rugged peaks) - 6 Octaves (rugged detail)
    let n0_mount = 1.0 - abs(n_f0);
    let mountain = 1.0 + (n0_mount * 1.3 - 0.3 + n_f0_2 * 0.35 + n_f0_4 * 0.2 + n_f0_8 * 0.08 + n_f0_16 * 0.04 + n_f0_32 * 0.02) * 8.0;

    // 5. Ocean elevation (deep basins)
    let ocean_floor = -5.0 + n_f0 * 1.0;

    // Mix land elevation (plains vs mountains)
    let land_elevation = mix(plains, mountain, mountain_factor * mountain_factor);

    // Mix ocean and land
    var elevation = mix(ocean_floor, land_elevation, land_mask);

    // 6. Terracing in mountains
    let terrace_pattern = sin(elevation * 1.5 + n_f0_4 * 0.4);
    let terrace_amp = 0.5 * mountain_factor;
    elevation += terrace_pattern * terrace_amp;

    // Scale by globals.noise_amplitude
    let disp = elevation * (globals.noise_amplitude * 0.025);
    return DisplacementData(disp, mountain_factor, land_mask, n_f0_12, n_f0);
}

fn get_heightmap_normal(pos_unit: vec3<f32>, h0: f32) -> vec3<f32> {
    let eps = 0.005;
    // Find orthogonal tangent vectors
    var tangent_x = vec3<f32>(1.0, 0.0, 0.0);
    if (abs(pos_unit.x) > 0.9) {
        tangent_x = vec3<f32>(0.0, 1.0, 0.0);
    }
    tangent_x = normalize(cross(pos_unit, tangent_x));
    let tangent_y = cross(pos_unit, tangent_x);

    let h1 = get_displacement(normalize(pos_unit + tangent_x * eps)).displacement;
    let h2 = get_displacement(normalize(pos_unit + tangent_y * eps)).displacement;

    let grad = tangent_x * (h1 - h0) / eps + tangent_y * (h2 - h0) / eps;
    return normalize(pos_unit - grad);
}

@vertex
fn vs_main(@builtin(vertex_index) vertex_id: u32) -> VertexOutput {
    var out: VertexOutput;

    // Pull vertex data from the storage buffer
    let v_data = vertices[vertex_id];
    let pos_world = v_data.position.xyz;
    let normal_world = v_data.normal.xyz;

    out.world_position = pos_world;
    out.normal = normal_world;
    out.clip_position = view_uniforms.view_proj * vec4<f32>(pos_world, 1.0);

    // Compute barycentric coordinates based on vertex ID modulo 3
    let mod3 = vertex_id % 3u;
    if (mod3 == 0u) {
        out.barycentric = vec3<f32>(1.0, 0.0, 0.0);
    } else if (mod3 == 1u) {
        out.barycentric = vec3<f32>(0.0, 1.0, 0.0);
    } else {
        out.barycentric = vec3<f32>(0.0, 0.0, 1.0);
    }

    return out;
}

fn get_biome_color(temp: f32, humid: f32, displacement: f32, slope_weight: f32, mountain_factor: f32) -> vec3<f32> {
    var color = vec3<f32>(0.0);

    // 1. Climate-based land biomes (Whittaker style)
    if (temp < 0.2) {
        // Coldest: Tundra / Ice Sheet
        if (humid < 0.3) {
            color = vec3<f32>(0.95, 0.95, 0.98); // Ice sheet (pure white)
        } else {
            color = vec3<f32>(0.85, 0.85, 0.88); // Snowy tundra (light grey)
        }
    } else if (temp < 0.45) {
        // Cold temperate: Boreal forest (Taiga) vs Cold desert
        if (humid < 0.25) {
            color = vec3<f32>(0.55, 0.50, 0.42); // Cold desert / steppe (pale brownish grey)
        } else if (humid < 0.6) {
            color = vec3<f32>(0.10, 0.28, 0.16); // Boreal forest (crisp pine green)
        } else {
            color = vec3<f32>(0.08, 0.26, 0.20); // Wet taiga (dark blue-green)
        }
    } else if (temp < 0.75) {
        // Warm temperate: Grasslands, woodlands, seasonal forests
        if (humid < 0.2) {
            color = vec3<f32>(0.65, 0.62, 0.46); // Temperate desert / dry grassland (sandy olive)
        } else if (humid < 0.5) {
            color = vec3<f32>(0.24, 0.48, 0.20); // Grassy plains / shrubland (lush light green)
        } else if (humid < 0.8) {
            color = vec3<f32>(0.12, 0.38, 0.14); // Deciduous forest (rich forest green)
        } else {
            color = vec3<f32>(0.08, 0.34, 0.16); // Temperate rainforest (deep green)
        }
    } else {
        // Hot tropical: Deserts, savannas, rainforests
        if (humid < 0.15) {
            color = vec3<f32>(0.82, 0.72, 0.55); // Subtropical desert (Sahara golden-sand)
        } else if (humid < 0.4) {
            color = vec3<f32>(0.50, 0.52, 0.25); // Savanna (dry golden-green)
        } else if (humid < 0.65) {
            color = vec3<f32>(0.14, 0.42, 0.16); // Tropical seasonal forest (bright warm green)
        } else {
            color = vec3<f32>(0.02, 0.50, 0.12); // Tropical rainforest / jungle (emerald green)
        }
    }

    // 2. Steep Rock Cliffs Override (slope-dependent, modulated by mountain factor to protect plains)
    let rock_weight = clamp((slope_weight - 0.22) / 0.15, 0.0, 1.0) * clamp(mountain_factor * 1.5, 0.0, 1.0);
    let rock_terrace = sin(displacement * 1.5) * 0.03;
    let rock_color = vec3<f32>(0.26, 0.25, 0.24) + vec3<f32>(rock_terrace);
    color = mix(color, rock_color, rock_weight);

    return color;
}

@fragment
fn fs_main(in: VertexOutput) -> @location(0) vec4<f32> {
    let radial_dir = normalize(in.world_position);
    let disp_data = get_displacement(radial_dir);
    let displacement = disp_data.displacement;
    let mountain_factor = disp_data.mountain_factor;
    let land_mask = disp_data.land_mask;
    let temp_noise = disp_data.temp_noise;
    let humid_noise = disp_data.humid_noise;

    var normal = radial_dir;
    if (displacement >= 0.0) {
        normal = get_heightmap_normal(radial_dir, displacement);
    }

    let view_dir = normalize(view_uniforms.camera_pos - in.world_position);
    let light_dir = normalize(view_uniforms.light_dir);

    let diffuse = max(dot(normal, light_dir), 0.0);
    let ambient = view_uniforms.ambient;

    let slope = 1.0 - dot(normal, radial_dir);

    // Climate Calculations
    // 1. Temperature: perturbed equator-to-pole gradient
    let perturbed_dir = normalize(radial_dir + temp_noise * 0.20);
    let t_base = 1.0 - abs(perturbed_dir.y);
    // Apply altitude cooling lapse rate (peaks are colder)
    let temp = clamp(t_base - max(displacement, 0.0) * 0.04, 0.0, 1.0);

    // 2. Humidity: reuse humid_noise (already sampled n_f0)
    let humid = clamp(humid_noise * 0.5 + 0.5, 0.0, 1.0);

    // Multi-biome coloring
    var biome_color = vec3<f32>(0.0);

    if (displacement < 0.0) {
        // Ocean: color based on temperature and depth
        let cold_ocean = vec3<f32>(0.06, 0.10, 0.18);
        let warm_ocean = vec3<f32>(0.01, 0.38, 0.46);
        let base_ocean = mix(cold_ocean, warm_ocean, temp);
        
        // Deepen the ocean color based on distance from land (smooth land_mask continental shelf)
        let depth_factor = clamp(1.0 - land_mask, 0.0, 1.0);
        let deep_ocean = vec3<f32>(0.005, 0.02, 0.08); // very dark navy
        
        biome_color = mix(base_ocean, deep_ocean, depth_factor * 0.9);
    } else if (displacement < 0.05) {
        // Beach: transition based on temperature
        let t_beach = displacement / 0.05;
        
        let cold_beach = vec3<f32>(0.25, 0.24, 0.24); // volcanic black sand
        let warm_beach = vec3<f32>(0.76, 0.68, 0.52); // golden sand
        let tropical_beach = vec3<f32>(0.86, 0.83, 0.76); // white sand
        
        var beach_color = vec3<f32>(0.0);
        if (temp < 0.35) {
            beach_color = cold_beach;
        } else if (temp < 0.7) {
            beach_color = warm_beach;
        } else {
            beach_color = tropical_beach;
        }
        
        // Blend beach with ocean at the shoreline
        let ocean_color_at_shore = mix(vec3<f32>(0.06, 0.10, 0.18), vec3<f32>(0.01, 0.38, 0.46), temp);
        biome_color = mix(ocean_color_at_shore, beach_color, t_beach);
    } else {
        // Land
        biome_color = get_biome_color(temp, humid, displacement, slope, mountain_factor);
    }

    // Shading / Lighting
    let shading = diffuse + ambient;
    var face_color = biome_color * shading;

    // 4. Specular highlight on water
    if (displacement < 0.0) {
        let half_dir = normalize(light_dir + view_dir);
        let specular = pow(max(dot(normal, half_dir), 0.0), 64.0) * 0.7;
        face_color = face_color + vec3<f32>(specular);
    }

    // 5. Rayleigh scattering representation (Rim Light / Atmospheric Glow)
    let rim = pow(1.0 - max(dot(view_dir, radial_dir), 0.0), 4.0);
    let rim_color = vec3<f32>(0.35, 0.55, 1.0) * rim * 0.45 * shading;
    face_color = face_color + rim_color;

    // 6. Ground Fog / Atmospheric Haze (fades out as camera goes to space)
    let distance_to_cam = distance(view_uniforms.camera_pos, in.world_position);
    let cam_height = length(view_uniforms.camera_pos);
    let fog_density = 0.002;
    let fog_factor = 1.0 - exp(-distance_to_cam * fog_density);
    let fog_intensity = clamp((150.0 - cam_height) / 50.0, 0.0, 1.0);
    let fog_color = vec3<f32>(0.55, 0.68, 0.85) * shading;
    let final_terrain_color = mix(face_color, fog_color, fog_factor * fog_intensity);

    // 7. Toggleable wireframe
    var final_color = final_terrain_color;
    if (view_uniforms.show_wireframe > 0.5) {
        let d = fwidth(in.barycentric);
        let a3 = smoothstep(vec3<f32>(0.0), d * 1.2, in.barycentric);
        let edge_factor = min(a3.x, min(a3.y, a3.z));
        let wireframe_color = vec3<f32>(1.0, 1.0, 1.0); // White
        let blend_factor = mix(0.5, 1.0, edge_factor);
        final_color = mix(wireframe_color, final_terrain_color, blend_factor);
    }

    return vec4<f32>(final_color, 1.0);
}
