// Generated by rust-gpu and naga. Do not edit.

struct Vec3Shared {
    member: f32,
    member_1: f32,
    member_2: f32,
}

fn snoise3_shared(param: Vec3Shared) -> f32 {
    var phi_757_: bool;
    var phi_772_: bool;
    var phi_787_: bool;
    var phi_830_: f32;
    var phi_842_: f32;
    var phi_854_: f32;
    var phi_866_: bool;
    var phi_881_: bool;
    var phi_896_: bool;
    var phi_938_: f32;
    var phi_950_: f32;
    var phi_962_: f32;
    var phi_1330_: bool;
    var phi_1345_: bool;
    var phi_1360_: bool;
    var phi_1375_: bool;
    var phi_1427_: Vec3Shared;
    var phi_1429_: Vec3Shared;
    var phi_1532_: Vec3Shared;
    var phi_1534_: Vec3Shared;
    var phi_1637_: Vec3Shared;
    var phi_1639_: Vec3Shared;
    var phi_1742_: Vec3Shared;
    var phi_1744_: Vec3Shared;

    let _e35 = (0.6666667f * ((param.member + param.member_1) + param.member_2));
    let _e36 = (_e35 - param.member);
    let _e37 = (_e35 - param.member_1);
    let _e38 = (_e35 - param.member_2);
    let _e39 = round(_e36);
    let _e40 = round(_e37);
    let _e41 = round(_e38);
    let _e42 = (_e36 - _e39);
    let _e43 = (_e37 - _e40);
    let _e44 = (_e38 - _e41);
    let _e45 = abs(_e42);
    let _e46 = abs(_e43);
    let _e47 = abs(_e44);
    if (_e46 != _e46) {
        phi_757_ = true;
    } else {
        phi_757_ = (_e47 >= _e46);
    }
    let _e51 = phi_757_;
    if (_e47 != _e47) {
        phi_772_ = true;
    } else {
        phi_772_ = (_e45 >= _e47);
    }
    let _e56 = phi_772_;
    if (_e45 != _e45) {
        phi_787_ = true;
    } else {
        phi_787_ = (_e46 >= _e45);
    }
    let _e61 = phi_787_;
    if (_e42 < 0f) {
        phi_830_ = -1f;
    } else {
        phi_830_ = select(0f, 1f, (_e42 > 0f));
    }
    let _e73 = phi_830_;
    if (_e43 < 0f) {
        phi_842_ = -1f;
    } else {
        phi_842_ = select(0f, 1f, (_e43 > 0f));
    }
    let _e78 = phi_842_;
    if (_e44 < 0f) {
        phi_854_ = -1f;
    } else {
        phi_854_ = select(0f, 1f, (_e44 > 0f));
    }
    let _e83 = phi_854_;
    let _e87 = (_e39 + (select(1f, 0f, (_e45 < select(_e46, _e47, _e51))) * _e73));
    let _e88 = (_e40 + (select(1f, 0f, (_e46 < select(_e47, _e45, _e56))) * _e78));
    let _e89 = (_e41 + (select(1f, 0f, (_e47 < select(_e45, _e46, _e61))) * _e83));
    let _e90 = (_e36 - _e87);
    let _e91 = (_e37 - _e88);
    let _e92 = (_e38 - _e89);
    let _e93 = (_e36 + 144.5f);
    let _e94 = (_e37 + 144.5f);
    let _e95 = (_e38 + 144.5f);
    let _e96 = round(_e93);
    let _e97 = round(_e94);
    let _e98 = round(_e95);
    let _e99 = (_e93 - _e96);
    let _e100 = (_e94 - _e97);
    let _e101 = (_e95 - _e98);
    let _e102 = abs(_e99);
    let _e103 = abs(_e100);
    let _e104 = abs(_e101);
    if (_e103 != _e103) {
        phi_866_ = true;
    } else {
        phi_866_ = (_e104 >= _e103);
    }
    let _e108 = phi_866_;
    if (_e104 != _e104) {
        phi_881_ = true;
    } else {
        phi_881_ = (_e102 >= _e104);
    }
    let _e113 = phi_881_;
    if (_e102 != _e102) {
        phi_896_ = true;
    } else {
        phi_896_ = (_e103 >= _e102);
    }
    let _e118 = phi_896_;
    if (_e99 < 0f) {
        phi_938_ = -1f;
    } else {
        phi_938_ = select(0f, 1f, (_e99 > 0f));
    }
    let _e130 = phi_938_;
    if (_e100 < 0f) {
        phi_950_ = -1f;
    } else {
        phi_950_ = select(0f, 1f, (_e100 > 0f));
    }
    let _e135 = phi_950_;
    if (_e101 < 0f) {
        phi_962_ = -1f;
    } else {
        phi_962_ = select(0f, 1f, (_e101 > 0f));
    }
    let _e140 = phi_962_;
    let _e144 = (_e96 + (select(1f, 0f, (_e102 < select(_e103, _e104, _e108))) * _e130));
    let _e145 = (_e97 + (select(1f, 0f, (_e103 < select(_e104, _e102, _e113))) * _e135));
    let _e146 = (_e98 + (select(1f, 0f, (_e104 < select(_e102, _e103, _e118))) * _e140));
    let _e147 = (_e93 - _e144);
    let _e148 = (_e94 - _e145);
    let _e149 = (_e95 - _e146);
    let _e162 = (_e39 - (floor((_e39 * 0.0034602077f)) * 289f));
    let _e163 = (_e87 - (floor((_e87 * 0.0034602077f)) * 289f));
    let _e164 = (_e96 - (floor((_e96 * 0.0034602077f)) * 289f));
    let _e165 = (_e144 - (floor((_e144 * 0.0034602077f)) * 289f));
    let _e178 = (_e162 - (floor((_e162 * 0.0034602077f)) * 289f));
    let _e179 = (_e163 - (floor((_e163 * 0.0034602077f)) * 289f));
    let _e180 = (_e164 - (floor((_e164 * 0.0034602077f)) * 289f));
    let _e181 = (_e165 - (floor((_e165 * 0.0034602077f)) * 289f));
    let _e190 = (_e178 * ((_e178 * 34f) + 133f));
    let _e191 = (_e179 * ((_e179 * 34f) + 133f));
    let _e192 = (_e180 * ((_e180 * 34f) + 133f));
    let _e193 = (_e181 * ((_e181 * 34f) + 133f));
    let _e210 = ((_e190 - (floor((_e190 * 0.0034602077f)) * 289f)) + _e40);
    let _e211 = ((_e191 - (floor((_e191 * 0.0034602077f)) * 289f)) + _e88);
    let _e212 = ((_e192 - (floor((_e192 * 0.0034602077f)) * 289f)) + _e97);
    let _e213 = ((_e193 - (floor((_e193 * 0.0034602077f)) * 289f)) + _e145);
    let _e226 = (_e210 - (floor((_e210 * 0.0034602077f)) * 289f));
    let _e227 = (_e211 - (floor((_e211 * 0.0034602077f)) * 289f));
    let _e228 = (_e212 - (floor((_e212 * 0.0034602077f)) * 289f));
    let _e229 = (_e213 - (floor((_e213 * 0.0034602077f)) * 289f));
    let _e242 = (_e226 - (floor((_e226 * 0.0034602077f)) * 289f));
    let _e243 = (_e227 - (floor((_e227 * 0.0034602077f)) * 289f));
    let _e244 = (_e228 - (floor((_e228 * 0.0034602077f)) * 289f));
    let _e245 = (_e229 - (floor((_e229 * 0.0034602077f)) * 289f));
    let _e254 = (_e242 * ((_e242 * 34f) + 133f));
    let _e255 = (_e243 * ((_e243 * 34f) + 133f));
    let _e256 = (_e244 * ((_e244 * 34f) + 133f));
    let _e257 = (_e245 * ((_e245 * 34f) + 133f));
    let _e274 = ((_e254 - (floor((_e254 * 0.0034602077f)) * 289f)) + _e41);
    let _e275 = ((_e255 - (floor((_e255 * 0.0034602077f)) * 289f)) + _e89);
    let _e276 = ((_e256 - (floor((_e256 * 0.0034602077f)) * 289f)) + _e98);
    let _e277 = ((_e257 - (floor((_e257 * 0.0034602077f)) * 289f)) + _e146);
    let _e290 = (_e274 - (floor((_e274 * 0.0034602077f)) * 289f));
    let _e291 = (_e275 - (floor((_e275 * 0.0034602077f)) * 289f));
    let _e292 = (_e276 - (floor((_e276 * 0.0034602077f)) * 289f));
    let _e293 = (_e277 - (floor((_e277 * 0.0034602077f)) * 289f));
    let _e306 = (_e290 - (floor((_e290 * 0.0034602077f)) * 289f));
    let _e307 = (_e291 - (floor((_e291 * 0.0034602077f)) * 289f));
    let _e308 = (_e292 - (floor((_e292 * 0.0034602077f)) * 289f));
    let _e309 = (_e293 - (floor((_e293 * 0.0034602077f)) * 289f));
    let _e318 = (_e306 * ((_e306 * 34f) + 133f));
    let _e319 = (_e307 * ((_e307 * 34f) + 133f));
    let _e320 = (_e308 * ((_e308 * 34f) + 133f));
    let _e321 = (_e309 * ((_e309 * 34f) + 133f));
    let _e334 = (_e318 - (floor((_e318 * 0.0034602077f)) * 289f));
    let _e335 = (_e319 - (floor((_e319 * 0.0034602077f)) * 289f));
    let _e336 = (_e320 - (floor((_e320 * 0.0034602077f)) * 289f));
    let _e337 = (_e321 - (floor((_e321 * 0.0034602077f)) * 289f));
    let _e350 = (_e334 - (floor((_e334 * 0.020833334f)) * 48f));
    let _e351 = (_e335 - (floor((_e335 * 0.020833334f)) * 48f));
    let _e352 = (_e336 - (floor((_e336 * 0.020833334f)) * 48f));
    let _e353 = (_e337 - (floor((_e337 * 0.020833334f)) * 48f));
    let _e374 = (0.5f - (((_e42 * _e42) + (_e43 * _e43)) + (_e44 * _e44)));
    let _e375 = (0.5f - (((_e90 * _e90) + (_e91 * _e91)) + (_e92 * _e92)));
    let _e376 = (0.5f - (((_e99 * _e99) + (_e100 * _e100)) + (_e101 * _e101)));
    let _e377 = (0.5f - (((_e147 * _e147) + (_e148 * _e148)) + (_e149 * _e149)));
    if (_e374 != _e374) {
        phi_1330_ = true;
    } else {
        phi_1330_ = (0f >= _e374);
    }
    let _e381 = phi_1330_;
    let _e382 = select(_e374, 0f, _e381);
    if (_e375 != _e375) {
        phi_1345_ = true;
    } else {
        phi_1345_ = (0f >= _e375);
    }
    let _e386 = phi_1345_;
    let _e387 = select(_e375, 0f, _e386);
    if (_e376 != _e376) {
        phi_1360_ = true;
    } else {
        phi_1360_ = (0f >= _e376);
    }
    let _e391 = phi_1360_;
    let _e392 = select(_e376, 0f, _e391);
    if (_e377 != _e377) {
        phi_1375_ = true;
    } else {
        phi_1375_ = (0f >= _e377);
    }
    let _e396 = phi_1375_;
    let _e397 = select(_e377, 0f, _e396);
    let _e398 = (_e382 * _e382);
    let _e399 = (_e387 * _e387);
    let _e400 = (_e392 * _e392);
    let _e401 = (_e397 * _e397);
    let _e406 = floor(_e350);
    let _e408 = floor((_e350 * 0.5f));
    let _e410 = floor((_e350 * 0.25f));
    let _e416 = (((_e406 - (floor((_e406 * 0.5f)) * 2f)) * 2f) - 1f);
    let _e422 = (((_e408 - (floor((_e408 * 0.5f)) * 2f)) * 2f) - 1f);
    let _e428 = (((_e410 - (floor((_e410 * 0.5f)) * 2f)) * 2f) - 1f);
    let _e430 = floor((_e350 * 0.0625f));
    let _e437 = select(0i, select(select(i32(_e430), i32(-2147483648), (_e430 < -2147483600f)), 2147483647i, (_e430 > 2147483500f)), (_e430 == _e430));
    if (_e437 == 0i) {
        phi_1429_ = Vec3Shared(0f, _e422, _e428);
    } else {
        if (_e437 == 1i) {
            phi_1427_ = Vec3Shared(_e416, 0f, _e428);
        } else {
            phi_1427_ = Vec3Shared(_e416, _e422, 0f);
        }
        let _e444 = phi_1427_;
        phi_1429_ = _e444;
    }
    let _e446 = phi_1429_;
    let _e448 = floor((_e350 * 0.125f));
    let _e452 = (_e448 - (floor((_e448 * 0.5f)) * 2f));
    let _e453 = (1f - _e452);
    let _e486 = ((1f - (0.04294244f * _e452)) * 32.802013f);
    let _e490 = floor(_e351);
    let _e492 = floor((_e351 * 0.5f));
    let _e494 = floor((_e351 * 0.25f));
    let _e500 = (((_e490 - (floor((_e490 * 0.5f)) * 2f)) * 2f) - 1f);
    let _e506 = (((_e492 - (floor((_e492 * 0.5f)) * 2f)) * 2f) - 1f);
    let _e512 = (((_e494 - (floor((_e494 * 0.5f)) * 2f)) * 2f) - 1f);
    let _e514 = floor((_e351 * 0.0625f));
    let _e521 = select(0i, select(select(i32(_e514), i32(-2147483648), (_e514 < -2147483600f)), 2147483647i, (_e514 > 2147483500f)), (_e514 == _e514));
    if (_e521 == 0i) {
        phi_1534_ = Vec3Shared(0f, _e506, _e512);
    } else {
        if (_e521 == 1i) {
            phi_1532_ = Vec3Shared(_e500, 0f, _e512);
        } else {
            phi_1532_ = Vec3Shared(_e500, _e506, 0f);
        }
        let _e528 = phi_1532_;
        phi_1534_ = _e528;
    }
    let _e530 = phi_1534_;
    let _e532 = floor((_e351 * 0.125f));
    let _e536 = (_e532 - (floor((_e532 * 0.5f)) * 2f));
    let _e537 = (1f - _e536);
    let _e570 = ((1f - (0.04294244f * _e536)) * 32.802013f);
    let _e574 = floor(_e352);
    let _e576 = floor((_e352 * 0.5f));
    let _e578 = floor((_e352 * 0.25f));
    let _e584 = (((_e574 - (floor((_e574 * 0.5f)) * 2f)) * 2f) - 1f);
    let _e590 = (((_e576 - (floor((_e576 * 0.5f)) * 2f)) * 2f) - 1f);
    let _e596 = (((_e578 - (floor((_e578 * 0.5f)) * 2f)) * 2f) - 1f);
    let _e598 = floor((_e352 * 0.0625f));
    let _e605 = select(0i, select(select(i32(_e598), i32(-2147483648), (_e598 < -2147483600f)), 2147483647i, (_e598 > 2147483500f)), (_e598 == _e598));
    if (_e605 == 0i) {
        phi_1639_ = Vec3Shared(0f, _e590, _e596);
    } else {
        if (_e605 == 1i) {
            phi_1637_ = Vec3Shared(_e584, 0f, _e596);
        } else {
            phi_1637_ = Vec3Shared(_e584, _e590, 0f);
        }
        let _e612 = phi_1637_;
        phi_1639_ = _e612;
    }
    let _e614 = phi_1639_;
    let _e616 = floor((_e352 * 0.125f));
    let _e620 = (_e616 - (floor((_e616 * 0.5f)) * 2f));
    let _e621 = (1f - _e620);
    let _e654 = ((1f - (0.04294244f * _e620)) * 32.802013f);
    let _e658 = floor(_e353);
    let _e660 = floor((_e353 * 0.5f));
    let _e662 = floor((_e353 * 0.25f));
    let _e668 = (((_e658 - (floor((_e658 * 0.5f)) * 2f)) * 2f) - 1f);
    let _e674 = (((_e660 - (floor((_e660 * 0.5f)) * 2f)) * 2f) - 1f);
    let _e680 = (((_e662 - (floor((_e662 * 0.5f)) * 2f)) * 2f) - 1f);
    let _e682 = floor((_e353 * 0.0625f));
    let _e689 = select(0i, select(select(i32(_e682), i32(-2147483648), (_e682 < -2147483600f)), 2147483647i, (_e682 > 2147483500f)), (_e682 == _e682));
    if (_e689 == 0i) {
        phi_1744_ = Vec3Shared(0f, _e674, _e680);
    } else {
        if (_e689 == 1i) {
            phi_1742_ = Vec3Shared(_e668, 0f, _e680);
        } else {
            phi_1742_ = Vec3Shared(_e668, _e674, 0f);
        }
        let _e696 = phi_1742_;
        phi_1744_ = _e696;
    }
    let _e698 = phi_1744_;
    let _e700 = floor((_e353 * 0.125f));
    let _e704 = (_e700 - (floor((_e700 * 0.5f)) * 2f));
    let _e705 = (1f - _e704);
    let _e738 = ((1f - (0.04294244f * _e704)) * 32.802013f);
    return (((((_e398 * _e398) * (((_e42 * (((_e446.member * 1.2247449f) + ((_e453 * _e416) + (_e452 * (_e446.member + ((_e422 * _e446.member_2) - (_e446.member_1 * _e428)))))) * _e486)) + (_e43 * (((_e446.member_1 * 1.2247449f) + ((_e453 * _e422) + (_e452 * (_e446.member_1 + ((_e428 * _e446.member) - (_e446.member_2 * _e416)))))) * _e486))) + (_e44 * (((_e446.member_2 * 1.2247449f) + ((_e453 * _e428) + (_e452 * (_e446.member_2 + ((_e416 * _e446.member_1) - (_e446.member * _e422)))))) * _e486)))) + ((_e399 * _e399) * (((_e90 * (((_e530.member * 1.2247449f) + ((_e537 * _e500) + (_e536 * (_e530.member + ((_e506 * _e530.member_2) - (_e530.member_1 * _e512)))))) * _e570)) + (_e91 * (((_e530.member_1 * 1.2247449f) + ((_e537 * _e506) + (_e536 * (_e530.member_1 + ((_e512 * _e530.member) - (_e530.member_2 * _e500)))))) * _e570))) + (_e92 * (((_e530.member_2 * 1.2247449f) + ((_e537 * _e512) + (_e536 * (_e530.member_2 + ((_e500 * _e530.member_1) - (_e530.member * _e506)))))) * _e570))))) + ((_e400 * _e400) * (((_e99 * (((_e614.member * 1.2247449f) + ((_e621 * _e584) + (_e620 * (_e614.member + ((_e590 * _e614.member_2) - (_e614.member_1 * _e596)))))) * _e654)) + (_e100 * (((_e614.member_1 * 1.2247449f) + ((_e621 * _e590) + (_e620 * (_e614.member_1 + ((_e596 * _e614.member) - (_e614.member_2 * _e584)))))) * _e654))) + (_e101 * (((_e614.member_2 * 1.2247449f) + ((_e621 * _e596) + (_e620 * (_e614.member_2 + ((_e584 * _e614.member_1) - (_e614.member * _e590)))))) * _e654))))) + ((_e401 * _e401) * (((_e147 * (((_e698.member * 1.2247449f) + ((_e705 * _e668) + (_e704 * (_e698.member + ((_e674 * _e698.member_2) - (_e698.member_1 * _e680)))))) * _e738)) + (_e148 * (((_e698.member_1 * 1.2247449f) + ((_e705 * _e674) + (_e704 * (_e698.member_1 + ((_e680 * _e698.member) - (_e698.member_2 * _e668)))))) * _e738))) + (_e149 * (((_e698.member_2 * 1.2247449f) + ((_e705 * _e680) + (_e704 * (_e698.member_2 + ((_e668 * _e698.member_1) - (_e698.member * _e674)))))) * _e738)))));
}