// WGSL Compute Shader for dynamic 3D isosphere subdivision, frustum culling, and displacement

struct Globals {
    camera_pos: vec3<f32>,
    planet_radius: f32,
    planet_center: vec3<f32>,
    noise_frequency: f32,
    noise_amplitude: f32,
    dummy: f32,
    frustum_planes: array<vec4<f32>, 6>,
}

struct VertexOutput {
    position: vec4<f32>,
    normal: vec4<f32>,
}

struct DrawIndexedIndirectArgs {
    index_count: atomic<u32>,
    instance_count: u32,
    first_index: u32,
    base_vertex: i32,
    first_instance: u32,
}

@group(0) @binding(0) var<uniform> globals: Globals;
@group(0) @binding(1) var<storage, read_write> out_vertices: array<VertexOutput>;
@group(0) @binding(2) var<storage, read_write> out_indices: array<u32>;
@group(0) @binding(3) var<storage, read_write> indirect_args: DrawIndexedIndirectArgs;
@group(0) @binding(4) var<storage, read_write> vertex_counter: atomic<u32>;

// Generated by rust-gpu and naga. Do not edit.

struct Vec3Shared {
    member: f32,
    member_1: f32,
    member_2: f32,
}

fn snoise3_shared(param: Vec3Shared) -> f32 {
    var phi_650_: bool;
    var phi_665_: bool;
    var phi_680_: bool;
    var phi_695_: bool;
    var phi_710_: bool;
    var phi_725_: bool;
    var phi_977_: bool;
    var phi_992_: bool;
    var phi_1007_: bool;
    var phi_1022_: bool;

    let _e29 = (0.33333334f * ((param.member + param.member_1) + param.member_2));
    let _e33 = floor((param.member + _e29));
    let _e34 = floor((param.member_1 + _e29));
    let _e35 = floor((param.member_2 + _e29));
    let _e41 = (0.16666667f * ((_e33 + _e34) + _e35));
    let _e42 = ((param.member - _e33) + _e41);
    let _e43 = ((param.member_1 - _e34) + _e41);
    let _e44 = ((param.member_2 - _e35) + _e41);
    let _e46 = select(1f, 0f, (_e42 < _e43));
    let _e48 = select(1f, 0f, (_e43 < _e44));
    let _e50 = select(1f, 0f, (_e44 < _e42));
    let _e51 = (1f - _e46);
    let _e52 = (1f - _e48);
    let _e53 = (1f - _e50);
    let _e54 = (_e46 != _e46);
    if _e54 {
        phi_650_ = true;
    } else {
        phi_650_ = (_e53 <= _e46);
    }
    let _e57 = phi_650_;
    let _e58 = select(_e46, _e53, _e57);
    let _e59 = (_e48 != _e48);
    if _e59 {
        phi_665_ = true;
    } else {
        phi_665_ = (_e51 <= _e48);
    }
    let _e62 = phi_665_;
    let _e63 = select(_e48, _e51, _e62);
    let _e64 = (_e50 != _e50);
    if _e64 {
        phi_680_ = true;
    } else {
        phi_680_ = (_e52 <= _e50);
    }
    let _e67 = phi_680_;
    let _e68 = select(_e50, _e52, _e67);
    if _e54 {
        phi_695_ = true;
    } else {
        phi_695_ = (_e53 >= _e46);
    }
    let _e71 = phi_695_;
    let _e72 = select(_e46, _e53, _e71);
    if _e59 {
        phi_710_ = true;
    } else {
        phi_710_ = (_e51 >= _e48);
    }
    let _e75 = phi_710_;
    let _e76 = select(_e48, _e51, _e75);
    if _e64 {
        phi_725_ = true;
    } else {
        phi_725_ = (_e52 >= _e50);
    }
    let _e79 = phi_725_;
    let _e80 = select(_e50, _e52, _e79);
    let _e84 = ((_e42 - _e58) + 0.16666667f);
    let _e85 = ((_e43 - _e63) + 0.16666667f);
    let _e86 = ((_e44 - _e68) + 0.16666667f);
    let _e90 = ((_e42 - _e72) + 0.33333334f);
    let _e91 = ((_e43 - _e76) + 0.33333334f);
    let _e92 = ((_e44 - _e80) + 0.33333334f);
    let _e93 = (_e42 - 0.5f);
    let _e94 = (_e43 - 0.5f);
    let _e95 = (_e44 - 0.5f);
    let _e105 = (_e33 - (floor((_e33 * 0.0034602077f)) * 289f));
    let _e106 = (_e34 - (floor((_e34 * 0.0034602077f)) * 289f));
    let _e107 = (_e35 - (floor((_e35 * 0.0034602077f)) * 289f));
    let _e108 = (_e107 + _e68);
    let _e109 = (_e107 + _e80);
    let _e110 = (_e107 + 1f);
    let _e119 = (((_e107 * 34f) + 1f) * _e107);
    let _e120 = (((_e108 * 34f) + 1f) * _e108);
    let _e121 = (((_e109 * 34f) + 1f) * _e109);
    let _e122 = (((_e110 * 34f) + 1f) * _e110);
    let _e139 = ((_e119 - (floor((_e119 * 0.0034602077f)) * 289f)) + _e106);
    let _e143 = (((_e120 - (floor((_e120 * 0.0034602077f)) * 289f)) + _e106) + _e63);
    let _e144 = (((_e121 - (floor((_e121 * 0.0034602077f)) * 289f)) + _e106) + _e76);
    let _e145 = (((_e122 - (floor((_e122 * 0.0034602077f)) * 289f)) + _e106) + 1f);
    let _e154 = (((_e139 * 34f) + 1f) * _e139);
    let _e155 = (((_e143 * 34f) + 1f) * _e143);
    let _e156 = (((_e144 * 34f) + 1f) * _e144);
    let _e157 = (((_e145 * 34f) + 1f) * _e145);
    let _e174 = ((_e154 - (floor((_e154 * 0.0034602077f)) * 289f)) + _e105);
    let _e178 = (((_e155 - (floor((_e155 * 0.0034602077f)) * 289f)) + _e105) + _e58);
    let _e179 = (((_e156 - (floor((_e156 * 0.0034602077f)) * 289f)) + _e105) + _e72);
    let _e180 = (((_e157 - (floor((_e157 * 0.0034602077f)) * 289f)) + _e105) + 1f);
    let _e189 = (((_e174 * 34f) + 1f) * _e174);
    let _e190 = (((_e178 * 34f) + 1f) * _e178);
    let _e191 = (((_e179 * 34f) + 1f) * _e179);
    let _e192 = (((_e180 * 34f) + 1f) * _e180);
    let _e205 = (_e189 - (floor((_e189 * 0.0034602077f)) * 289f));
    let _e206 = (_e190 - (floor((_e190 * 0.0034602077f)) * 289f));
    let _e207 = (_e191 - (floor((_e191 * 0.0034602077f)) * 289f));
    let _e208 = (_e192 - (floor((_e192 * 0.0034602077f)) * 289f));
    let _e221 = (_e205 - (floor((_e205 * 0.020408165f)) * 49f));
    let _e222 = (_e206 - (floor((_e206 * 0.020408165f)) * 49f));
    let _e223 = (_e207 - (floor((_e207 * 0.020408165f)) * 49f));
    let _e224 = (_e208 - (floor((_e208 * 0.020408165f)) * 49f));
    let _e229 = floor((_e221 * 0.14285715f));
    let _e230 = floor((_e222 * 0.14285715f));
    let _e231 = floor((_e223 * 0.14285715f));
    let _e232 = floor((_e224 * 0.14285715f));
    let _e249 = ((_e229 * 0.2857143f) + -0.9285714f);
    let _e250 = ((_e230 * 0.2857143f) + -0.9285714f);
    let _e251 = ((_e231 * 0.2857143f) + -0.9285714f);
    let _e252 = ((_e232 * 0.2857143f) + -0.9285714f);
    let _e257 = ((floor((_e221 - (_e229 * 7f))) * 0.2857143f) + -0.9285714f);
    let _e258 = ((floor((_e222 - (_e230 * 7f))) * 0.2857143f) + -0.9285714f);
    let _e259 = ((floor((_e223 - (_e231 * 7f))) * 0.2857143f) + -0.9285714f);
    let _e260 = ((floor((_e224 - (_e232 * 7f))) * 0.2857143f) + -0.9285714f);
    let _e273 = ((1f - abs(_e249)) - abs(_e257));
    let _e274 = ((1f - abs(_e250)) - abs(_e258));
    let _e275 = ((1f - abs(_e251)) - abs(_e259));
    let _e276 = ((1f - abs(_e252)) - abs(_e260));
    let _e309 = -(select(1f, 0f, (0f < _e273)));
    let _e310 = -(select(1f, 0f, (0f < _e274)));
    let _e311 = -(select(1f, 0f, (0f < _e275)));
    let _e312 = -(select(1f, 0f, (0f < _e276)));
    let _e317 = (_e249 + (((floor(_e249) * 2f) + 1f) * _e309));
    let _e318 = (_e257 + (((floor(_e257) * 2f) + 1f) * _e309));
    let _e319 = (_e250 + (((floor(_e250) * 2f) + 1f) * _e310));
    let _e320 = (_e258 + (((floor(_e258) * 2f) + 1f) * _e310));
    let _e325 = (_e251 + (((floor(_e251) * 2f) + 1f) * _e311));
    let _e326 = (_e259 + (((floor(_e259) * 2f) + 1f) * _e311));
    let _e327 = (_e252 + (((floor(_e252) * 2f) + 1f) * _e312));
    let _e328 = (_e260 + (((floor(_e260) * 2f) + 1f) * _e312));
    let _e353 = (1.7928429f - ((((_e317 * _e317) + (_e318 * _e318)) + (_e273 * _e273)) * 0.85373473f));
    let _e354 = (1.7928429f - ((((_e319 * _e319) + (_e320 * _e320)) + (_e274 * _e274)) * 0.85373473f));
    let _e355 = (1.7928429f - ((((_e325 * _e325) + (_e326 * _e326)) + (_e275 * _e275)) * 0.85373473f));
    let _e356 = (1.7928429f - ((((_e327 * _e327) + (_e328 * _e328)) + (_e276 * _e276)) * 0.85373473f));
    let _e389 = (0.6f - (((_e42 * _e42) + (_e43 * _e43)) + (_e44 * _e44)));
    let _e390 = (0.6f - (((_e84 * _e84) + (_e85 * _e85)) + (_e86 * _e86)));
    let _e391 = (0.6f - (((_e90 * _e90) + (_e91 * _e91)) + (_e92 * _e92)));
    let _e392 = (0.6f - (((_e93 * _e93) + (_e94 * _e94)) + (_e95 * _e95)));
    if (_e389 != _e389) {
        phi_977_ = true;
    } else {
        phi_977_ = (0f >= _e389);
    }
    let _e396 = phi_977_;
    let _e397 = select(_e389, 0f, _e396);
    if (_e390 != _e390) {
        phi_992_ = true;
    } else {
        phi_992_ = (0f >= _e390);
    }
    let _e401 = phi_992_;
    let _e402 = select(_e390, 0f, _e401);
    if (_e391 != _e391) {
        phi_1007_ = true;
    } else {
        phi_1007_ = (0f >= _e391);
    }
    let _e406 = phi_1007_;
    let _e407 = select(_e391, 0f, _e406);
    if (_e392 != _e392) {
        phi_1022_ = true;
    } else {
        phi_1022_ = (0f >= _e392);
    }
    let _e411 = phi_1022_;
    let _e412 = select(_e392, 0f, _e411);
    let _e413 = (_e397 * _e397);
    let _e414 = (_e402 * _e402);
    let _e415 = (_e407 * _e407);
    let _e416 = (_e412 * _e412);
    return (105f * (((((_e413 * _e413) * ((((_e317 * _e353) * _e42) + ((_e318 * _e353) * _e43)) + ((_e273 * _e353) * _e44))) + ((_e414 * _e414) * ((((_e319 * _e354) * _e84) + ((_e320 * _e354) * _e85)) + ((_e274 * _e354) * _e86)))) + ((_e415 * _e415) * ((((_e325 * _e355) * _e90) + ((_e326 * _e355) * _e91)) + ((_e275 * _e355) * _e92)))) + ((_e416 * _e416) * ((((_e327 * _e356) * _e93) + ((_e328 * _e356) * _e94)) + ((_e276 * _e356) * _e95)))));
}

// Normalized icosahedron base geometry
const X: f32 = 0.525731112119133606;
const Z: f32 = 0.850650808352039932;

const BASE_VERTICES = array<vec3<f32>, 12>(
    vec3<f32>(-X, Z, 0.0), vec3<f32>(X, Z, 0.0), vec3<f32>(-X, -Z, 0.0), vec3<f32>(X, -Z, 0.0),
    vec3<f32>(0.0, -X, Z), vec3<f32>(0.0, X, Z), vec3<f32>(0.0, -X, -Z), vec3<f32>(0.0, X, -Z),
    vec3<f32>(Z, 0.0, -X), vec3<f32>(Z, 0.0, X), vec3<f32>(-Z, 0.0, -X), vec3<f32>(-Z, 0.0, X)
);

const BASE_FACES = array<vec3<u32>, 20>(
    vec3<u32>(0, 11, 5), vec3<u32>(0, 5, 1), vec3<u32>(0, 1, 7), vec3<u32>(0, 7, 10), vec3<u32>(0, 10, 11),
    vec3<u32>(1, 5, 9), vec3<u32>(5, 11, 4), vec3<u32>(11, 10, 2), vec3<u32>(10, 7, 6), vec3<u32>(7, 1, 8),
    vec3<u32>(3, 9, 4), vec3<u32>(3, 4, 2), vec3<u32>(3, 2, 6), vec3<u32>(3, 6, 8), vec3<u32>(3, 8, 9),
    vec3<u32>(4, 9, 5), vec3<u32>(2, 4, 11), vec3<u32>(6, 2, 10), vec3<u32>(8, 6, 7), vec3<u32>(9, 8, 1)
);

fn get_barycentric_point(A: vec3<f32>, B: vec3<f32>, C: vec3<f32>, u_val: f32, v_val: f32) -> vec3<f32> {
    let w = 1.0 - u_val - v_val;
    return normalize(A * w + B * u_val + C * v_val);
}

// Displace a normalized sphere coordinate using 3D Simplex noise
fn get_displaced_vertex(pos_unit: vec3<f32>) -> vec3<f32> {
    let p = pos_unit * globals.noise_frequency;
    let noise_val = snoise3_shared(Vec3Shared(p.x, p.y, p.z));
    // Displace outwards from center
    let height = globals.planet_radius + noise_val * globals.noise_amplitude;
    return globals.planet_center + pos_unit * height;
}

@compute @workgroup_size(20, 1, 1)
fn main(@builtin(global_invocation_id) global_id: vec3<u32>) {
    let face_id = global_id.x;
    if (face_id >= 20u) {
        return;
    }

    // Get the base vertices of the icosahedron face
    let A = BASE_VERTICES[BASE_FACES[face_id].x];
    let B = BASE_VERTICES[BASE_FACES[face_id].y];
    let C = BASE_VERTICES[BASE_FACES[face_id].z];

    // Compute bounding sphere of this base face
    let center = (A + B + C) / 3.0;
    let world_center = globals.planet_center + center * globals.planet_radius;
    let bounding_radius = max(distance(center, A), max(distance(center, B), distance(center, C))) * globals.planet_radius + globals.noise_amplitude;

    // 1. Frustum Culling
    var culled = false;
    for (var i = 0u; i < 6u; i = i + 1u) {
        let plane = globals.frustum_planes[i];
        let dist = dot(plane.xyz, world_center) + plane.w;
        if (dist < -bounding_radius) {
            culled = true;
            break;
        }
    }

    if (culled) {
        return;
    }

    // 2. Dynamic LOD based on distance to camera
    let dist_to_cam = distance(globals.camera_pos, world_center);
    let h_above_surface = max(0.0, dist_to_cam - globals.planet_radius);

    // Calculate subdivision level (12 distinct levels of detail, max increased by 8x to 320)
    var LOD_SEGMENTS = array<u32, 12>(1u, 2u, 4u, 8u, 16u, 28u, 48u, 80u, 128u, 180u, 240u, 320u);
    let t_val = clamp(1.0 - h_above_surface / 2.0, 0.0, 1.0);
    let index = u32(clamp(t_val * 11.0, 0.0, 11.0));
    let S = LOD_SEGMENTS[index];

    // 3. Dynamic Tessellation
    // Loop over the subdivision grid and output triangles
    for (var j = 0u; j < S; j = j + 1u) {
        for (var i = 0u; i < S - j; i = i + 1u) {
            // Triangle 1: (i, j) -> (i+1, j) -> (i, j+1)
            output_triangle(A, B, C, i, j, i + 1u, j, i, j + 1u, S);

            // Triangle 2: (i+1, j) -> (i+1, j+1) -> (i, j+1)
            if (i + j + 1u < S) {
                output_triangle(A, B, C, i + 1u, j, i + 1u, j + 1u, i, j + 1u, S);
            }
        }
    }
}

// Generate a single flat-shaded triangle, allocate storage space, and write buffers
fn output_triangle(
    A: vec3<f32>, B: vec3<f32>, C: vec3<f32>,
    u1: u32, v1: u32,
    u2: u32, v2: u32,
    u3: u32, v3: u32,
    S: u32
) {
    // Generate normalized points
    let p1_unit = get_barycentric_point(A, B, C, f32(u1)/f32(S), f32(v1)/f32(S));
    let p2_unit = get_barycentric_point(A, B, C, f32(u2)/f32(S), f32(v2)/f32(S));
    let p3_unit = get_barycentric_point(A, B, C, f32(u3)/f32(S), f32(v3)/f32(S));

    // Apply displacement
    let pos1 = get_displaced_vertex(p1_unit);
    let pos2 = get_displaced_vertex(p2_unit);
    let pos3 = get_displaced_vertex(p3_unit);

    // Flat normal calculation
    let flat_normal = normalize(cross(pos2 - pos1, pos3 - pos1));

    // Allocate storage slots
    let v_start = atomicAdd(&vertex_counter, 3u);
    let i_start = atomicAdd(&indirect_args.index_count, 3u);

    // Safety checks against buffer limits (MAX_VERTICES = 2097152, MAX_INDICES = 4194304)
    if (v_start + 3u > 2097152u || i_start + 3u > 4194304u) {
        return;
    }

    // Write vertex positions & normals
    out_vertices[v_start].position = vec4<f32>(pos1, 1.0);
    out_vertices[v_start].normal = vec4<f32>(flat_normal, 0.0);

    out_vertices[v_start + 1u].position = vec4<f32>(pos2, 1.0);
    out_vertices[v_start + 1u].normal = vec4<f32>(flat_normal, 0.0);

    out_vertices[v_start + 2u].position = vec4<f32>(pos3, 1.0);
    out_vertices[v_start + 2u].normal = vec4<f32>(flat_normal, 0.0);

    // Write index data
    out_indices[i_start] = v_start;
    out_indices[i_start + 1u] = v_start + 1u;
    out_indices[i_start + 2u] = v_start + 2u;
}
