// WGSL Compute Shader for dynamic 3D isosphere subdivision, frustum culling, and displacement

struct Globals {
    camera_pos: vec3<f32>,
    planet_radius: f32,
    planet_center: vec3<f32>,
    noise_frequency: f32,
    noise_amplitude: f32,
    dummy: f32,
    frustum_planes: array<vec4<f32>, 6>,
}

struct VertexOutput {
    position: vec4<f32>,
    normal: vec4<f32>,
}

struct DrawIndirectArgs {
    vertex_count: atomic<u32>,
    instance_count: u32,
    first_vertex: u32,
    first_instance: u32,
}

struct PassUniforms {
    depth: u32,
}

struct Triangle {
    v0: vec4<f32>,
    v1: vec4<f32>,
    v2: vec4<f32>,
}

@group(0) @binding(0) var<uniform> globals: Globals;
@group(0) @binding(1) var<storage, read_write> out_vertices: array<VertexOutput>;
@group(0) @binding(2) var<storage, read_write> indirect_args: DrawIndirectArgs;
@group(0) @binding(3) var<uniform> pass_uniforms: PassUniforms;
@group(0) @binding(4) var<storage, read> base_faces: array<Triangle>;
@group(0) @binding(5) var<storage, read_write> input_queue: array<Triangle>;
@group(0) @binding(6) var<storage, read_write> output_queue: array<Triangle>;
@group(0) @binding(7) var<storage, read> input_counter: u32;
@group(0) @binding(8) var<storage, read_write> output_counter: atomic<u32>;

// Generated by rust-gpu and naga. Do not edit.

struct Vec3Shared {
    member: f32,
    member_1: f32,
    member_2: f32,
}

fn snoise3_shared(param: Vec3Shared) -> f32 {
    var phi_650_: bool;
    var phi_665_: bool;
    var phi_680_: bool;
    var phi_695_: bool;
    var phi_710_: bool;
    var phi_725_: bool;
    var phi_977_: bool;
    var phi_992_: bool;
    var phi_1007_: bool;
    var phi_1022_: bool;

    let _e29 = (0.33333334f * ((param.member + param.member_1) + param.member_2));
    let _e33 = floor((param.member + _e29));
    let _e34 = floor((param.member_1 + _e29));
    let _e35 = floor((param.member_2 + _e29));
    let _e41 = (0.16666667f * ((_e33 + _e34) + _e35));
    let _e42 = ((param.member - _e33) + _e41);
    let _e43 = ((param.member_1 - _e34) + _e41);
    let _e44 = ((param.member_2 - _e35) + _e41);
    let _e46 = select(1f, 0f, (_e42 < _e43));
    let _e48 = select(1f, 0f, (_e43 < _e44));
    let _e50 = select(1f, 0f, (_e44 < _e42));
    let _e51 = (1f - _e46);
    let _e52 = (1f - _e48);
    let _e53 = (1f - _e50);
    let _e54 = (_e46 != _e46);
    if _e54 {
        phi_650_ = true;
    } else {
        phi_650_ = (_e53 <= _e46);
    }
    let _e57 = phi_650_;
    let _e58 = select(_e46, _e53, _e57);
    let _e59 = (_e48 != _e48);
    if _e59 {
        phi_665_ = true;
    } else {
        phi_665_ = (_e51 <= _e48);
    }
    let _e62 = phi_665_;
    let _e63 = select(_e48, _e51, _e62);
    let _e64 = (_e50 != _e50);
    if _e64 {
        phi_680_ = true;
    } else {
        phi_680_ = (_e52 <= _e50);
    }
    let _e67 = phi_680_;
    let _e68 = select(_e50, _e52, _e67);
    if _e54 {
        phi_695_ = true;
    } else {
        phi_695_ = (_e53 >= _e46);
    }
    let _e71 = phi_695_;
    let _e72 = select(_e46, _e53, _e71);
    if _e59 {
        phi_710_ = true;
    } else {
        phi_710_ = (_e51 >= _e48);
    }
    let _e75 = phi_710_;
    let _e76 = select(_e48, _e51, _e75);
    if _e64 {
        phi_725_ = true;
    } else {
        phi_725_ = (_e52 >= _e50);
    }
    let _e79 = phi_725_;
    let _e80 = select(_e50, _e52, _e79);
    let _e84 = ((_e42 - _e58) + 0.16666667f);
    let _e85 = ((_e43 - _e63) + 0.16666667f);
    let _e86 = ((_e44 - _e68) + 0.16666667f);
    let _e90 = ((_e42 - _e72) + 0.33333334f);
    let _e91 = ((_e43 - _e76) + 0.33333334f);
    let _e92 = ((_e44 - _e80) + 0.33333334f);
    let _e93 = (_e42 - 0.5f);
    let _e94 = (_e43 - 0.5f);
    let _e95 = (_e44 - 0.5f);
    let _e105 = (_e33 - (floor((_e33 * 0.0034602077f)) * 289f));
    let _e106 = (_e34 - (floor((_e34 * 0.0034602077f)) * 289f));
    let _e107 = (_e35 - (floor((_e35 * 0.0034602077f)) * 289f));
    let _e108 = (_e107 + _e68);
    let _e109 = (_e107 + _e80);
    let _e110 = (_e107 + 1f);
    let _e119 = (((_e107 * 34f) + 1f) * _e107);
    let _e120 = (((_e108 * 34f) + 1f) * _e108);
    let _e121 = (((_e109 * 34f) + 1f) * _e109);
    let _e122 = (((_e110 * 34f) + 1f) * _e110);
    let _e139 = ((_e119 - (floor((_e119 * 0.0034602077f)) * 289f)) + _e106);
    let _e143 = (((_e120 - (floor((_e120 * 0.0034602077f)) * 289f)) + _e106) + _e63);
    let _e144 = (((_e121 - (floor((_e121 * 0.0034602077f)) * 289f)) + _e106) + _e76);
    let _e145 = (((_e122 - (floor((_e122 * 0.0034602077f)) * 289f)) + _e106) + 1f);
    let _e154 = (((_e139 * 34f) + 1f) * _e139);
    let _e155 = (((_e143 * 34f) + 1f) * _e143);
    let _e156 = (((_e144 * 34f) + 1f) * _e144);
    let _e157 = (((_e145 * 34f) + 1f) * _e145);
    let _e174 = ((_e154 - (floor((_e154 * 0.0034602077f)) * 289f)) + _e105);
    let _e178 = (((_e155 - (floor((_e155 * 0.0034602077f)) * 289f)) + _e105) + _e58);
    let _e179 = (((_e156 - (floor((_e156 * 0.0034602077f)) * 289f)) + _e105) + _e72);
    let _e180 = (((_e157 - (floor((_e157 * 0.0034602077f)) * 289f)) + _e105) + 1f);
    let _e189 = (((_e174 * 34f) + 1f) * _e174);
    let _e190 = (((_e178 * 34f) + 1f) * _e178);
    let _e191 = (((_e179 * 34f) + 1f) * _e179);
    let _e192 = (((_e180 * 34f) + 1f) * _e180);
    let _e205 = (_e189 - (floor((_e189 * 0.0034602077f)) * 289f));
    let _e206 = (_e190 - (floor((_e190 * 0.0034602077f)) * 289f));
    let _e207 = (_e191 - (floor((_e191 * 0.0034602077f)) * 289f));
    let _e208 = (_e192 - (floor((_e192 * 0.0034602077f)) * 289f));
    let _e221 = (_e205 - (floor((_e205 * 0.020408165f)) * 49f));
    let _e222 = (_e206 - (floor((_e206 * 0.020408165f)) * 49f));
    let _e223 = (_e207 - (floor((_e207 * 0.020408165f)) * 49f));
    let _e224 = (_e208 - (floor((_e208 * 0.020408165f)) * 49f));
    let _e229 = floor((_e221 * 0.14285715f));
    let _e230 = floor((_e222 * 0.14285715f));
    let _e231 = floor((_e223 * 0.14285715f));
    let _e232 = floor((_e224 * 0.14285715f));
    let _e249 = ((_e229 * 0.2857143f) + -0.9285714f);
    let _e250 = ((_e230 * 0.2857143f) + -0.9285714f);
    let _e251 = ((_e231 * 0.2857143f) + -0.9285714f);
    let _e252 = ((_e232 * 0.2857143f) + -0.9285714f);
    let _e257 = ((floor((_e221 - (_e229 * 7f))) * 0.2857143f) + -0.9285714f);
    let _e258 = ((floor((_e222 - (_e230 * 7f))) * 0.2857143f) + -0.9285714f);
    let _e259 = ((floor((_e223 - (_e231 * 7f))) * 0.2857143f) + -0.9285714f);
    let _e260 = ((floor((_e224 - (_e232 * 7f))) * 0.2857143f) + -0.9285714f);
    let _e273 = ((1f - abs(_e249)) - abs(_e257));
    let _e274 = ((1f - abs(_e250)) - abs(_e258));
    let _e275 = ((1f - abs(_e251)) - abs(_e259));
    let _e276 = ((1f - abs(_e252)) - abs(_e260));
    let _e309 = -(select(1f, 0f, (0f < _e273)));
    let _e310 = -(select(1f, 0f, (0f < _e274)));
    let _e311 = -(select(1f, 0f, (0f < _e275)));
    let _e312 = -(select(1f, 0f, (0f < _e276)));
    let _e317 = (_e249 + (((floor(_e249) * 2f) + 1f) * _e309));
    let _e318 = (_e257 + (((floor(_e257) * 2f) + 1f) * _e309));
    let _e319 = (_e250 + (((floor(_e250) * 2f) + 1f) * _e310));
    let _e320 = (_e258 + (((floor(_e258) * 2f) + 1f) * _e310));
    let _e325 = (_e251 + (((floor(_e251) * 2f) + 1f) * _e311));
    let _e326 = (_e259 + (((floor(_e259) * 2f) + 1f) * _e311));
    let _e327 = (_e252 + (((floor(_e252) * 2f) + 1f) * _e312));
    let _e328 = (_e260 + (((floor(_e260) * 2f) + 1f) * _e312));
    let _e353 = (1.7928429f - ((((_e317 * _e317) + (_e318 * _e318)) + (_e273 * _e273)) * 0.85373473f));
    let _e354 = (1.7928429f - ((((_e319 * _e319) + (_e320 * _e320)) + (_e274 * _e274)) * 0.85373473f));
    let _e355 = (1.7928429f - ((((_e325 * _e325) + (_e326 * _e326)) + (_e275 * _e275)) * 0.85373473f));
    let _e356 = (1.7928429f - ((((_e327 * _e327) + (_e328 * _e328)) + (_e276 * _e276)) * 0.85373473f));
    let _e389 = (0.6f - (((_e42 * _e42) + (_e43 * _e43)) + (_e44 * _e44)));
    let _e390 = (0.6f - (((_e84 * _e84) + (_e85 * _e85)) + (_e86 * _e86)));
    let _e391 = (0.6f - (((_e90 * _e90) + (_e91 * _e91)) + (_e92 * _e92)));
    let _e392 = (0.6f - (((_e93 * _e93) + (_e94 * _e94)) + (_e95 * _e95)));
    if (_e389 != _e389) {
        phi_977_ = true;
    } else {
        phi_977_ = (0f >= _e389);
    }
    let _e396 = phi_977_;
    let _e397 = select(_e389, 0f, _e396);
    if (_e390 != _e390) {
        phi_992_ = true;
    } else {
        phi_992_ = (0f >= _e390);
    }
    let _e401 = phi_992_;
    let _e402 = select(_e390, 0f, _e401);
    if (_e391 != _e391) {
        phi_1007_ = true;
    } else {
        phi_1007_ = (0f >= _e391);
    }
    let _e406 = phi_1007_;
    let _e407 = select(_e391, 0f, _e406);
    if (_e392 != _e392) {
        phi_1022_ = true;
    } else {
        phi_1022_ = (0f >= _e392);
    }
    let _e411 = phi_1022_;
    let _e412 = select(_e392, 0f, _e411);
    let _e413 = (_e397 * _e397);
    let _e414 = (_e402 * _e402);
    let _e415 = (_e407 * _e407);
    let _e416 = (_e412 * _e412);
    return (105f * (((((_e413 * _e413) * ((((_e317 * _e353) * _e42) + ((_e318 * _e353) * _e43)) + ((_e273 * _e353) * _e44))) + ((_e414 * _e414) * ((((_e319 * _e354) * _e84) + ((_e320 * _e354) * _e85)) + ((_e274 * _e354) * _e86)))) + ((_e415 * _e415) * ((((_e325 * _e355) * _e90) + ((_e326 * _e355) * _e91)) + ((_e275 * _e355) * _e92)))) + ((_e416 * _e416) * ((((_e327 * _e356) * _e93) + ((_e328 * _e356) * _e94)) + ((_e276 * _e356) * _e95)))));
}

fn get_barycentric_point(A: vec3<f32>, B: vec3<f32>, C: vec3<f32>, u_val: f32, v_val: f32) -> vec3<f32> {
    let w = 1.0 - u_val - v_val;
    return normalize(A * w + B * u_val + C * v_val);
}

// Displace a normalized sphere coordinate using 3D Simplex noise
fn get_displaced_vertex(pos_unit: vec3<f32>) -> vec3<f32> {
    let p = pos_unit * globals.noise_frequency;
    let noise_val = snoise3_shared(Vec3Shared(p.x, p.y, p.z));
    // Displace outwards from center
    let height = globals.planet_radius + noise_val * globals.noise_amplitude;
    return globals.planet_center + pos_unit * height;
}

@compute @workgroup_size(64, 1, 1)
fn main(@builtin(global_invocation_id) global_id: vec3<u32>) {
    let face_id = global_id.x;

    // Determine the active count of input triangles
    var input_count = 20u;
    if (pass_uniforms.depth > 0u) {
        input_count = input_counter;
    }

    // Early exit if this invocation exceeds the input queue
    if (face_id >= input_count) {
        return;
    }

    // Read triangle from appropriate buffer
    var tri: Triangle;
    if (pass_uniforms.depth == 0u) {
        tri = base_faces[face_id];
    } else {
        tri = input_queue[face_id];
    }

    let A = tri.v0.xyz;
    let B = tri.v1.xyz;
    let C = tri.v2.xyz;

    // Compute bounding sphere of this triangle
    let center = (A + B + C) / 3.0;
    let world_center = globals.planet_center + normalize(center) * globals.planet_radius;
    let bounding_radius = max(distance(center, A), max(distance(center, B), distance(center, C))) * globals.planet_radius + globals.noise_amplitude;

    // 1. Frustum Culling
    var culled = false;
    for (var i = 0u; i < 6u; i = i + 1u) {
        let plane = globals.frustum_planes[i];
        let dist = dot(plane.xyz, world_center) + plane.w;
        if (dist < -bounding_radius) {
            culled = true;
            break;
        }
    }

    if (culled) {
        return;
    }

    // 2. Dynamic LOD based on distance to camera
    let dist_to_cam = distance(globals.camera_pos, world_center);
    let h_above_surface = max(0.0, dist_to_cam - globals.planet_radius);

    // Split threshold halves at each depth level
    let split_dist = 12.0 / pow(2.0, f32(pass_uniforms.depth));

    // Split if we are close enough and haven't hit maximum depth (8)
    let should_split = h_above_surface < split_dist && pass_uniforms.depth < 8u;

    if (should_split) {
        // Compute edge midpoints projected onto the sphere
        let m0 = vec4<f32>(normalize(A + B), 0.0);
        let m1 = vec4<f32>(normalize(B + C), 0.0);
        let m2 = vec4<f32>(normalize(C + A), 0.0);

        // Allocate slots in the output queue
        let out_idx = atomicAdd(&output_counter, 4u);

        // Prevent queue overflow (buffer capacity MAX_QUEUE_SIZE = 524288)
        if (out_idx + 4u <= 524288u) {
            output_queue[out_idx] = Triangle(tri.v0, m0, m2);
            output_queue[out_idx + 1u] = Triangle(vec4<f32>(B, 0.0), m1, m0);
            output_queue[out_idx + 2u] = Triangle(vec4<f32>(C, 0.0), m2, m1);
            output_queue[out_idx + 3u] = Triangle(m0, m1, m2);
        }
    } else {
        // Output leaf triangle to vertex buffer
        let p1 = get_displaced_vertex(A);
        let p2 = get_displaced_vertex(B);
        let p3 = get_displaced_vertex(C);

        // Flat normal
        let flat_normal = normalize(cross(p2 - p1, p3 - p1));

        // Allocate slots in the vertex buffer
        let v_start = atomicAdd(&indirect_args.vertex_count, 3u);

        // Prevent vertex buffer overflow (MAX_VERTICES = 2097152)
        if (v_start + 3u <= 2097152u) {
            out_vertices[v_start] = VertexOutput(vec4<f32>(p1, 1.0), vec4<f32>(flat_normal, 0.0));
            out_vertices[v_start + 1u] = VertexOutput(vec4<f32>(p2, 1.0), vec4<f32>(flat_normal, 0.0));
            out_vertices[v_start + 2u] = VertexOutput(vec4<f32>(p3, 1.0), vec4<f32>(flat_normal, 0.0));
        }
    }
}
